n0: go run main.go -p 5000
n1: go run main.go -p 5001
n2: go run main.go -p 5002
# n3: go run main.go -p 5003
# n4: go run main.go -p 5004
# n5: go run main.go -p 5005
# n6: go run main.go -p 5006
# n7: go run main.go -p 5007
# n8: go run main.go -p 5008
# n9: go run main.go -p 5009
